import { NextPage } from "next";
import Head from "next/head";


const Home:NextPage = ()=>{
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcomo to <a href="https://nextjs.org">Nextjs</a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident
          maxime nihil aliquam voluptatum deserunt nam ducimus aliquid
          accusantium totam id.
        </p>
      </main>
    </>
  );
  }

  export default Home
